import HashMap from "./hash-map";
import HashSet from "./hash-set";

const testMap = new HashMap();
testMap.set('snake', 'black');
testMap.set('frog', 'green');
testMap.set('owl', 'brown');
testMap.set('giraffe', 'yellow');
testMap.set('zebra', 'striped');
// testMap.set('cow', 'spotted');
// testMap.set('penguin', 'tuxedo');
// testMap.set('dolphin', 'grey');
// testMap.set('tiger', 'orange');
// testMap.set('octopus', 'purple');
// testMap.get('frog');
// testMap.has('zebra');
// testMap.remove('owl');
// testMap.length();
// testMap.clear();
// testMap.keys();
// testMap.values();
// testMap.entries();
console.log(testMap);

const testSet = new HashSet();
// testSet.add('snake');
// testSet.add('frog');
// testSet.add('owl');
// testSet.add('giraffe');
// testSet.add('zebra');
testSet.add('cow');
testSet.add('penguin');
testSet.add('dolphin');
testSet.add('tiger');
testSet.add('octopus');
// testSet.has('tiger');
// testSet.remove('dolphin');
// testSet.length();
// testSet.clear();
// testSet.keys();
console.log(testSet);
