import HashMap from "./hash-map";
import HashSet from "./hash-set";

const testMap = new HashMap();
testMap.set('snake', 'black');
testMap.set('frog', 'green');
testMap.set('owl', 'brown');
testMap.set('giraffe', 'yellow');
testMap.set('zebra', 'striped');
testMap.set('cow', 'spotted');
testMap.set('penguin', 'tuxedo');
testMap.set('dolphin', 'grey');
testMap.set('tiger', 'orange');
testMap.set('octopus', 'purple');
// testMap.get('frog');
// testMap.has('tiger');
// testMap.remove('owl');
// testMap.length();
// testMap.clear();
// testMap.keys();
// testMap.values();
// testMap.entries();
console.log(testMap);

// const testSet = new HashSet();
// testSet.set('snake', 'black');
// testSet.set('frog', 'green');
// testSet.set('owl', 'brown');
// testSet.set('giraffe', 'yellow');
// testSet.set('zebra', 'striped');
// testSet.set('cow', 'spotted');
// testSet.set('penguin', 'tuxedo');
// testSet.set('dolphin', 'grey');
// testSet.set('tiger', 'orange');
// testSet.set('octopus', 'purple');
// testSet.has('tiger');
// testSet.remove('owl');
// testSet.length();
// testSet.clear();
// testSet.keys();
// console.log(testSet);
